"""
Django settings for wangleiproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dbp2b7_glri9%)t$$%=of-zmf+#i4^*3j7*11s&eqwm1*-=9ao'
# 密钥
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# 将来上线改为False

ALLOWED_HOSTS = ['*']

#以下是一些常见的情况，需要配置ALLOWED_HOSTS：
#开发环境：在开发过程中，如果需要在本地网络中让其他设备访问开发服务器，或者使用自定义域名进行开发测试，就需要配置ALLOWED_HOSTS。例如，将ALLOWED_HOSTS设置为['*']（不推荐在生产环境中使用），或者指定具体的开发服务器 IP 地址或域名。
#生产环境：当将 Django 应用部署到生产服务器上时，必须正确配置ALLOWED_HOSTS，以确保只有合法的域名或 IP 地址能够访问应用。这是为了防止恶意域名访问你的应用，提高系统的安全性。例如，将ALLOWED_HOSTS设置为['example.com', 'www.example.com']，只允许example.com和www.example.com这两个域名访问应用。


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',#与总urls有关
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wlapp.apps.WlappConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'captcha',
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'
# 后加的配置

# 应用程序
MIDDLEWARE = [
    'wlapp.middleware.visit_log_middle',# 处于第一个可以将所有的应用时间都计算
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',    
    'wlapp.middleware.login_check_middleware',
]
# 中间件

ROOT_URLCONF = 'wangleiproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wangleiproject.wsgi.application'
# 启动方式 wsgi和asgi，wsgi

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wlproject',
        'USER':'wluser',
        "PASSWORD":'Wl123456',
        "HOST":"localhost",
        'PORT':'3306',
        'OPTIONS':{
            'charset':'utf8mb4' # 解决中文乱码
        } 
    }
}
# 数据库

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# 认证配置

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
# 语言 当把en-us改为zh-hans时候，展示中文

TIME_ZONE = 'UTC'
# 时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置静态文件路径
MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'
