# Generated by Django 5.1.3 on 2025-03-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=120, verbose_name="用户名")),
                ("password", models.CharField(max_length=60, verbose_name="密码")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "男"), (1, "女")], verbose_name="性别"
                    ),
                ),
                ("role", models.CharField(max_length=20, verbose_name="角色")),
                ("create_time", models.DateField(verbose_name="创建时间")),
            ],
        ),
    ]
