# Generated by Django 5.1.3 on 2025-03-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wlapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=18, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(choices=[(1, "男"), (0, "女")], verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="normal", max_length=20, verbose_name="角色"),
        ),
    ]
