# Generated by Django 5.1.3 on 2025-03-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wlapp", "0004_user_age2_alter_user_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age2",
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=18, verbose_name="年龄"),
        ),
    ]
