# Generated by Django 5.1.3 on 2025-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlapp', '0005_remove_user_age1_remove_user_age2_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('normal', '普通用户')], default='normal', max_length=20, verbose_name='角色'),
        ),
    ]
