# Generated by Django 5.1.3 on 2025-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='访问IP')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('curr_time', models.CharField(max_length=20, verbose_name='当前时间')),
                ('path', models.CharField(max_length=128, verbose_name='访问路径')),
                ('used_time', models.FloatField(verbose_name='访问耗时')),
            ],
        ),
    ]
