# Generated by Django 5.1.3 on 2025-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlapp', '0009_user_head_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TianQiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('max_temperature', models.IntegerField(verbose_name='最高温度')),
                ('min_temperature', models.IntegerField(verbose_name='最低温度')),
                ('weather', models.CharField(max_length=128, verbose_name='天气')),
                ('wind_direction', models.CharField(max_length=128, verbose_name='风向')),
                ('week', models.CharField(max_length=128, verbose_name='风力')),
            ],
        ),
    ]
