# Generated by Django 5.1.3 on 2025-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlapp', '0010_tianqidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tianqidata',
            name='week',
            field=models.CharField(blank=True, max_length=128, verbose_name='星期'),
        ),
    ]
